spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        binder:
          brokers: localhost:29092
      bindings:
        producer-out-0:
          destination: test-topic-inbound
          producer:
            useNativeEncoding: true
        consumer-in-0:
          destination: test-topic-inbound
          consumer:
            use-native-decoding: true